[project]
name = "django-magic-context"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

[dependency-groups]
test = [
    "pytest>=8.3.4",
]

